"""Shared agent tool classification constants."""

CONFIRMATION_TOOLS = {
    "write_file",
    "replace_in_file",
    "rename_file",
    "delete_file",
    "run_shell_command",
    "web_fetch",
    "git_commit",
    "git_checkout",
    "git_stash",
    "add_dependency",
    "remove_dependency",
    "batch_replace",
    "multi_edit",
    "apply_patch",
    "format_code",
    "run_docker",
    "database_query",
    "refactor_code",
    "deploy",
    "schedule_task",
    "save_memory",
    "forget_memory",
    "add_tool",
    "remove_tool",
    "add_skill",
    "remove_skill",
    "send_telegram",
}

READ_ONLY_TOOLS = {
    "read_file",
    "read_many_files",
    "list_directory",
    "glob_files",
    "grep_search",
    "search_files",
    "git_status",
    "git_diff",
    "git_log",
    "git_branch",
    "find_definition",
    "find_references",
    "get_project_info",
    "repo_map",
    "list_dependencies",
    "plan_task",
    "load_context",
    "analyze_code",
    "generate_tests",
    "load_memory",
    "list_schedules",
    "list_skills",
    "list_custom_tools",
}

LIGHT_CONFIRM_TOOLS = {
    "git_add",
    "run_tests",
    "lint_code",
    "type_check",
    "save_context",
}
