"""Declarative command metadata for the slash-command registry."""

DEFAULT_COMMAND_SPECS = [
    {
        "names": ["/help", "/h", "/?"],
        "handler_name": "_cmd_help",
        "description": "Show help and available commands",
        "category": "navigation",
        "accepts_args": True,
        "telegram_safe": True,
    },
    {
        "names": ["/tools"],
        "handler_name": "_cmd_tools",
        "description": "List all available tools",
        "category": "navigation",
        "accepts_args": False,
        "telegram_safe": True,
    },
    {
        "names": ["/clear", "/c"],
        "handler_name": "_cmd_clear",
        "description": "Clear conversation history",
        "category": "conversation",
        "accepts_args": False,
        "telegram_safe": True,
    },
    {
        "names": ["/config", "/provider", "/swap"],
        "handler_name": "_cmd_config",
        "description": "Change provider or API key",
        "category": "provider",
        "accepts_args": False,
        "telegram_safe": False,
    },
    {
        "names": ["/switch", "/model"],
        "handler_name": "_cmd_switch",
        "description": "Quick switch provider/model",
        "category": "provider",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/free"],
        "handler_name": "_cmd_free",
        "description": "Switch to free OpenRouter model",
        "category": "provider",
        "accepts_args": False,
        "telegram_safe": True,
    },
    {
        "names": ["/ratelimit", "/rl", "/limit"],
        "handler_name": "_cmd_ratelimit",
        "description": "Set API call limit per turn",
        "category": "provider",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/theme", "/palette"],
        "handler_name": "_cmd_theme",
        "description": "Pick UI color palette",
        "category": "appearance",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/font", "/glyphs"],
        "handler_name": "_cmd_font",
        "description": "Pick font / glyph profile",
        "category": "appearance",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/animations", "/anim"],
        "handler_name": "_cmd_animations",
        "description": "Set animation level",
        "category": "appearance",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/exit", "/quit", "/q"],
        "handler_name": "_cmd_exit",
        "description": "Exit RadSim",
        "category": "session",
        "accepts_args": False,
        "telegram_safe": False,
    },
    {
        "names": ["/kill", "/stop", "/abort"],
        "handler_name": "_cmd_kill",
        "description": "EMERGENCY: Immediately stop agent",
        "category": "session",
        "accepts_args": False,
        "telegram_safe": False,
    },
    {
        "names": ["/new", "/fresh"],
        "handler_name": "_cmd_new",
        "description": "Start new conversation with fresh context",
        "category": "conversation",
        "accepts_args": False,
        "telegram_safe": True,
    },
    {
        "names": ["/setup", "/onboarding"],
        "handler_name": "_cmd_setup",
        "description": "Re-run the setup wizard",
        "category": "provider",
        "accepts_args": False,
        "telegram_safe": False,
    },
    {
        "names": ["/good", "/+"],
        "handler_name": "_cmd_good",
        "description": "Mark last response as good (positive feedback)",
        "category": "learning",
        "accepts_args": False,
        "telegram_safe": True,
    },
    {
        "names": ["/improve", "/-"],
        "handler_name": "_cmd_improve",
        "description": "Mark last response for improvement",
        "category": "learning",
        "accepts_args": False,
        "telegram_safe": True,
    },
    {
        "names": ["/stats"],
        "handler_name": "_cmd_stats",
        "description": "Show learning statistics",
        "category": "learning",
        "accepts_args": False,
        "telegram_safe": True,
    },
    {
        "names": ["/report"],
        "handler_name": "_cmd_report",
        "description": "Export detailed learning report",
        "category": "learning",
        "accepts_args": False,
        "telegram_safe": True,
    },
    {
        "names": ["/audit"],
        "handler_name": "_cmd_audit",
        "description": "Audit learned preferences",
        "category": "learning",
        "accepts_args": False,
        "telegram_safe": True,
    },
    {
        "names": ["/reset"],
        "handler_name": "_cmd_reset",
        "description": "Reset learned data (usage: /reset <category>)",
        "category": "learning",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/preferences", "/prefs"],
        "handler_name": "_cmd_preferences",
        "description": "Show learned preferences",
        "category": "learning",
        "accepts_args": False,
        "telegram_safe": True,
    },
    {
        "names": ["/trust"],
        "handler_name": "_cmd_trust",
        "description": "View or reset learned confirmation trust",
        "category": "learning",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/skill", "/skills"],
        "handler_name": "_cmd_skill",
        "description": "Configure custom skills/instructions",
        "category": "customization",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/commands", "/cmds"],
        "handler_name": "_cmd_commands",
        "description": "List all available commands",
        "category": "navigation",
        "accepts_args": False,
        "telegram_safe": True,
    },
    {
        "names": ["/memory", "/mem"],
        "handler_name": "_cmd_memory",
        "description": "Manage persistent memory",
        "category": "memory",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/teach", "/t"],
        "handler_name": "_cmd_teach",
        "description": "Toggle Teach Me mode (explains while coding)",
        "category": "modes",
        "accepts_args": False,
        "telegram_safe": True,
    },
    {
        "names": ["/modes"],
        "handler_name": "_cmd_modes",
        "description": "List all available modes",
        "category": "modes",
        "accepts_args": False,
        "telegram_safe": True,
    },
    {
        "names": ["/awake", "/caffeinate"],
        "handler_name": "_cmd_awake",
        "description": "Toggle stay-awake mode (macOS)",
        "category": "modes",
        "accepts_args": False,
        "telegram_safe": True,
    },
    {
        "names": ["/show"],
        "handler_name": "_cmd_show",
        "description": "Show last written file content",
        "category": "modes",
        "accepts_args": True,
        "telegram_safe": True,
    },
    {
        "names": ["/selfmod", "/self"],
        "handler_name": "_cmd_selfmod",
        "description": "View/edit RadSim source and custom prompt",
        "category": "customization",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/telegram", "/tg"],
        "handler_name": "_cmd_telegram",
        "description": "Configure Telegram notifications",
        "category": "integrations",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/settings", "/set"],
        "handler_name": "_cmd_settings",
        "description": "View/change agent settings",
        "category": "configuration",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/evolve", "/self-improve"],
        "handler_name": "_cmd_evolve",
        "description": "Review self-improvement proposals",
        "category": "learning",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/complexity", "/cx"],
        "handler_name": "_cmd_complexity",
        "description": "Complexity budget & scoring",
        "category": "analysis",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/stress", "/adversarial"],
        "handler_name": "_cmd_stress",
        "description": "Adversarial code review",
        "category": "analysis",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/archaeology", "/arch", "/dead"],
        "handler_name": "_cmd_archaeology",
        "description": "Find dead code & zombies",
        "category": "analysis",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/plan", "/p"],
        "handler_name": "_cmd_plan",
        "description": "Structured plan-confirm-execute workflow",
        "category": "planning",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/panning", "/pan"],
        "handler_name": "_cmd_panning",
        "description": "Brain-dump processing & synthesis",
        "category": "planning",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/background", "/bg"],
        "handler_name": "_cmd_background",
        "description": "View/manage background sub-agent jobs",
        "category": "background",
        "accepts_args": True,
        "telegram_safe": True,
    },
    {
        "names": ["/job", "/jobs", "/cron"],
        "handler_name": "_cmd_job",
        "description": "Manage scheduled cron jobs",
        "category": "background",
        "accepts_args": True,
        "telegram_safe": False,
    },
    {
        "names": ["/mcp"],
        "handler_name": "_cmd_mcp",
        "description": "Manage MCP server connections",
        "category": "integrations",
        "accepts_args": True,
        "telegram_safe": False,
    },
]


TELEGRAM_SAFE_COMMANDS = {
    spec["names"][0]: spec["description"]
    for spec in DEFAULT_COMMAND_SPECS
    if spec["telegram_safe"]
}


COMMAND_HINTS = {
    "model": [
        ("/switch", "Quick switch model"),
        ("/config", "Full configuration"),
        ("/free", "Use free model"),
    ],
    "error": [
        ("/clear", "Clear and retry"),
        ("/new", "Fresh start"),
    ],
    "slow": [
        ("/switch", "Try faster model"),
        ("/free", "Use free model"),
    ],
    "feedback": [
        ("/good", "Mark as good"),
        ("/improve", "Mark for improvement"),
    ],
    "help": [
        ("/help", "Full help"),
        ("/tools", "Available tools"),
        ("/commands", "All commands"),
    ],
    "code": [
        ("/skill add", "Add coding preference"),
        ("/preferences", "See learned style"),
        ("/complexity", "Check complexity budget"),
        ("/stress", "Adversarial review"),
        ("/archaeology", "Find dead code"),
    ],
    "planning": [
        ("/plan", "Create/manage plans"),
        ("/panning", "Brain-dump processing"),
    ],
}
