"""RadSim learning through one event store and one retrieval service."""

from .events import (
    LearningEvent,
    ReflectionEngine,
    TaskOutcome,
    TaskOutcomeTracker,
    TaskReflection,
    get_improvement_opportunities,
    get_reflection_engine,
    record_revert,
    reflect_on_completion,
)
from .preference_learner import (
    PreferenceLearner,
    adjust_prompt_for_preferences,
    get_learned_preferences,
    get_preference_learner,
    record_feedback,
)
from .proposals import (
    ImprovementProposal,
    ProposalEngine,
    SelfImprover,
    analyze_and_propose_improvements,
    approve_proposal,
    get_pending_proposals,
    get_self_improver,
    reject_proposal,
)
from .retrieval import (
    ErrorAnalyzer,
    FewShotAssembler,
    TaskExample,
    ToolExecution,
    ToolOptimizer,
    check_similar_error,
    flush_tool_optimizer,
    get_error_analyzer,
    get_error_patterns,
    get_examples_for_task,
    get_few_shot_assembler,
    get_tool_optimizer,
    get_tool_rankings,
    inject_examples_into_prompt,
    rank_learning_events,
    record_error,
    suggest_tool_chain,
    text_similarity,
    tfidf_cosine_scores,
    track_tool_execution,
    verified_success_events,
)
from .store import (
    LearningAnalytics,
    LearningStore,
    export_learning_report,
    get_analytics,
    get_learning_stats,
    get_learning_store,
    reset_learning_category,
)

__all__ = [
    "LearningEvent",
    "LearningStore",
    "TaskOutcome",
    "TaskOutcomeTracker",
    "TaskReflection",
    "get_learning_store",
    # Error Analyzer
    "ErrorAnalyzer",
    "get_error_analyzer",
    "record_error",
    "check_similar_error",
    "get_error_patterns",
    # Preference Learner
    "PreferenceLearner",
    "get_preference_learner",
    "record_feedback",
    "get_learned_preferences",
    "adjust_prompt_for_preferences",
    # Few-Shot Assembler
    "FewShotAssembler",
    "get_few_shot_assembler",
    "get_examples_for_task",
    "inject_examples_into_prompt",
    # Tool Optimizer
    "ToolOptimizer",
    "get_tool_optimizer",
    "flush_tool_optimizer",
    "track_tool_execution",
    "suggest_tool_chain",
    "get_tool_rankings",
    "ToolExecution",
    # Reflection Engine
    "ReflectionEngine",
    "get_reflection_engine",
    "reflect_on_completion",
    "get_improvement_opportunities",
    "record_revert",
    # Self-Improver
    "ImprovementProposal",
    "ProposalEngine",
    "SelfImprover",
    "get_self_improver",
    "analyze_and_propose_improvements",
    "get_pending_proposals",
    "approve_proposal",
    "reject_proposal",
    # Analytics
    "LearningAnalytics",
    "get_analytics",
    "get_learning_stats",
    "export_learning_report",
    "reset_learning_category",
    # Shared retrieval
    "rank_learning_events",
    "text_similarity",
    "tfidf_cosine_scores",
    "verified_success_events",
    "TaskExample",
]
